sudo: false
language: go
script:
  - unset $GOPATH
  - go get 
  - git clone https://github.com/ShigekiKarita/hugo -b dlang --depth 1
  - cd hugo && go install && cd -
  - ~/go/bin/hugo
  - touch public/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  on:
    branch: master
