sudo: false
language: go
script:
  - git clone https://github.com/ShigekiKarita/hugo -b dlang --depth 1
  - cd hugo
  - go install
  - cd -
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  on:
    branch: master
