sudo: false
# language: go
script:
  # install hugo
  - wget https://github.com/ShigekiKarita/hugo/releases/download/dlang-v1/hugo.tar.xz
  - tar -xvf hugo.tar.gz
  - ./hugo
  # - INIT_DIR=$(pwd)
  # - mkdir $HOME/src
  # - cd $HOME/src
  # - git clone https://github.com/ShigekiKarita/hugo --depth 1 -b dlang
  # - cd hugo
  # - go install
  # - cd $INIT_DIR
  # build page
  # - $GOPATH/bin/hugo
  - touch public/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  on:
    branch: master
