sudo: false
language: go
script:
  - git clone https://github.com/gohugoio/hugo --depth 1 -b release-0.55.4
  - cd hugo
  - sed -i 's/v.0.6.3/v0.6.4-0.20190428191540-1327f9145ea6/' ./go.mod
  - go install
  - cd -
  - $GOPATH/bin/hugo
  - touch public/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  on:
    branch: master
